import abouts from './abouts'
import brands from './brands'
import contact from './contact'
import skills from './skills'
import works from './works'
import experiences from './experiences'
import testimonials from './testimonials'
import workExperience from './workExperience'
import resume from './resume'
export const schemaTypes = [abouts,brands,contact,skills,works,experiences,testimonials,workExperience,resume]
